version: '3'
services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=django_market
  web:
    image: entsllor/dj-market-main
    build: ./project
    volumes:
      # static files
      - ./project/static/:/usr/src/dj-market/static/:rw
      # media files
      - ./project/media/:/usr/src/dj-market/media/:rw
      # log files
      - ./project/log/:/usr/src/dj-market/log/:rw
    env_file:
      - ./project/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./project/static/:/var/www/static/:ro
      - ./project/media/:/var/www/media/:rw
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  postgres_data:
